name: ant
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          8,  # Minimum supported
          11, # Java LTS
          16, # Last version
          17  # Most recent version
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v2.1.0
          with:
              java-version: ${{ matrix.java }}
              distribution: zulu
        - name: Build with Ant
          run: ant -noinput -buildfile build.xml dist-jar
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          if: ${{ matrix.java == 8 && matrix.os == 'ubuntu-latest' }}
          with:
            name: standalone-jar
            path: dist/arrayVisualizer.jar
