name: maven
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          8,  # Minimum supported
          11,   # Current Java LTS
          15,   # Last version
          16    # Most recent version
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Build with Maven
        run: mvn clean install -f pom.xml
      - name: Upload shaded artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.java == 8 && matrix.os == 'ubuntu-latest' }}
        with:
          name: shaded-artifact
          path: target/arrayv-*.jar
      - name: Upload original artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.java == 8 && matrix.os == 'ubuntu-latest' }}
        with:
          name: original-artifact
          path: target/original-arrayv-*.jar
